### ISSUE TITLE
Recognised licence plates always miss last character

### ISSUE THREAD

**Issue by Dan1001** [DoubangoTelecom/ultimateALPR-SDK#141] opened 2021-04-08 15:09 UTC
Hi,

This is an impressive SDK, but I'm puzzled that recognised plates always come back with the last character replaced by an asterisk *. Is that a bug or a limitation of the free version?

Dan

**Comment by DoubangoTelecom** [comment] 2021-04-08 15:12
Duplicate of #13

**Closed by DoubangoTelecom** 2021-04-08 15:12 UTC
