### ISSUE TITLE
recognizer.py is showing '*' instead of last character of any detected plate

### ISSUE THREAD

**Issue by brodwix** [DoubangoTelecom/ultimateALPR-SDK#259] opened 2022-07-06 18:49 UTC
Hello, I'm trying to run the python example. I'm using Ubuntu 18.04, and I created an anaconda environment in order to test it with python 3.8. Also I've downloaded libtensorflow_r1.14 and moved the files to the binaries folder (binaries/linux/x86_64).

I run the program with the shared comand:
`PYTHONPATH=$PYTHONPATH:.:../../../python LD_LIBRARY_PATH=.:$LD_LIBRARY_PATH python ../../../samples/python/recognizer/recognizer.py --image ../../../assets/images/lic_us_1280x720.jpg 
`
The car from the original image has the number: 3PEDLM4
But the recognizer.py result shows me this: 3PEDLM*

I wish to know how to fix this issue. 
Thanks in advance

**Comment by DoubangoTelecom** [comment] 2022-07-06 19:10
Duplicate of #229

**Closed by DoubangoTelecom** 2022-07-06 19:10 UTC
