### ISSUE TITLE
Unable to get last character in Results

### ISSUE THREAD

**Issue by bhargavravat** [DoubangoTelecom/ultimateALPR-SDK#68] opened 2020-07-03 10:25 UTC
Hi @DoubangoTelecom : 

I tried exploring **recognition executable** with multiple indian number plates. It works fine _except it prints * in place of last digit._ 

What can be the possible solution for it?

Here is the **input image** ..
![image](https://user-images.githubusercontent.com/11025174/86460176-85003d80-bd45-11ea-9422-f032b4886def.png)

Here is the **output :** 
![image](https://user-images.githubusercontent.com/11025174/86460236-a19c7580-bd45-11ea-85de-929c3d6481f9.png)

**Comment by DoubangoTelecom** [comment] 2020-07-03 10:41
Duplicate of #13

**Closed by DoubangoTelecom** 2020-07-03 10:41 UTC
