### ISSUE TITLE
"[TFLite] ValidateBoxes in trouble" log and no way to supress it. 

### ISSUE THREAD

**Issue by minusplusminus** [DoubangoTelecom/ultimateALPR-SDK#140] opened 2021-03-26 15:53 UTC
Hi,

I'm testing your 3.3 repo on Ubuntu and Raspberry pi 4. On ubuntu it runs just fine. The code is the same and the video stream is the same.  But on raspbian I get  the following message in Python:

```
[TFLite] ValidateBoxes in trouble: -0.000215>=-0.000215 || 0.951639>=0.951639
```

Its fine that Tensorflow has this issue, but I want to surpress this output. I tried to change the debug level to  fatal it still doesn't dissappear.

**Comment by DoubangoTelecom** [comment] 2021-03-27 02:12
You can ignore the message. You cannot suppress it using log level because we used printf for  output. See issue #135

**Comment by DoubangoTelecom** [comment] 2021-03-27 04:49
Is the license plate correctly returned when the is printed?

**Comment by DoubangoTelecom** [comment] 2021-03-30 12:12
Duplicate of #135

**Comment by DoubangoTelecom** [comment] 2021-04-20 14:41
In the latest tensorflow code they have just change ">=" to ">" and according to the note they have added our patch is correct: https://github.com/tensorflow/tensorflow/blob/0b2560e217cf5bc7c9f931a3185c9c8e3f2e9d5e/tensorflow/lite/kernels/detection_postprocess.cc#L388

So, I don't thing the irregularities are caused by the changes. Please share a sample image if you have one.

**Closed** 2021-04-22 02:15 UTC
