### ISSUE TITLE
How to install "_ultimateAlprSdk" in Python?

### ISSUE THREAD

**Issue by rahulsharma22-ops** [DoubangoTelecom/ultimateALPR-SDK#24] opened 2020-01-06 13:18 UTC
I want to run the Python version of this code. The code is trying to import "_ultimateAlprSdk" but this does not exist. How can I install it? 

Also, I really do not understand, the whole library documentation. I am a bit new, can someone (Author or a community member), write a short tutorial about running it in Python.

**Comment by DoubangoTelecom** [comment] 2020-01-06 15:03
Duplicate of #7

**Closed by DoubangoTelecom** 2020-01-06 15:03 UTC

**Comment by DoubangoTelecom** [comment] 2020-08-07 06:55
Hello,

For information we have released the Python documentation in version 2.11.0. Recognizer sample in python: https://github.com/DoubangoTelecom/ultimateALPR-SDK/tree/master/samples/python/recognizer <https://github.com/DoubangoTelecom/ultimateALPR-SDK/tree/master/samples/python/recognizer>

Regards,
