### ISSUE TITLE
Asterisk replaces the last digit of detected plate number

### ISSUE THREAD

**Issue by ashjaymohsin** [DoubangoTelecom/ultimateALPR-SDK#276] opened 2023-05-02 15:31 UTC
When I run the sample recognizer.py, all of the detected number plates have their last digits replaced by an asterisk. What is causing this issue ?

**Comment by DoubangoTelecom** [comment] 2023-05-02 17:47
Duplicate of #275

**Closed by DoubangoTelecom** 2023-05-02 17:47 UTC
