### ISSUE TITLE
Unable to run python file

### ISSUE THREAD

**Issue by bhargavravat** [DoubangoTelecom/ultimateALPR-SDK#78] opened 2020-07-15 07:08 UTC
Hi @DoubangoTelecom :

I am trying to run sample file however unable to run the code. 

Here is the output log of the file:

`ultimateAlprSdk.py:13: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
Traceback (most recent call last):
  File "ultimateAlprSdk.py", line 16, in swig_import_helper
    fp, pathname, description = imp.find_module('_ultimateAlprSdk', [dirname(__file__)])
  File "/usr/lib/python3.8/imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_ultimateAlprSdk'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "ultimateAlprSdk.py", line 26, in <module>
    _ultimateAlprSdk = swig_import_helper()
  File "ultimateAlprSdk.py", line 18, in swig_import_helper
    import _ultimateAlprSdk
ModuleNotFoundError: No module named '_ultimateAlprSdk'
`

**Comment by DoubangoTelecom** [comment] 2020-07-15 07:35
Duplicate of #7

**Closed by DoubangoTelecom** 2020-07-15 07:35 UTC

**Comment by wesimet** [comment] 2020-09-06 15:51
Hi @DoubangoTelecom :

I am trying to run sample file however unable to run the code (on windows // ultimateALPR-SDK, *** Version 2.11.0 ***).

Error: No module named '_ultimateAlprSdk'.

What should I do?
Thank you in advance

**Comment by DoubangoTelecom** [comment] 2020-09-06 20:26
"_ultimateAlpr" is the extension file. The documentation is pretty clear that you have to build it: https://github.com/DoubangoTelecom/ultimateALPR-SDK/tree/master/samples/python/recognizer#prerequisite
