### ISSUE TITLE
Error: Unable to find '../swig.i'

### ISSUE THREAD

**Issue by bhargavravat** [DoubangoTelecom/ultimateALPR-SDK#79] opened 2020-07-20 11:50 UTC
Hi @DoubangoTelecom : 

I am trying to execute python file : 

Here is the command which i am using : ` /bin/swig -python python.i `

Erros Output  Log : `root@997c26f5ec30:/data/ultimateALPR-SDK/python# /bin/swig -python python.i 
python.i:7: Error: Unable to find '../swig.i'
`

Here is the screen shot of the error :

![image](https://user-images.githubusercontent.com/11025174/87934685-23fa9880-caad-11ea-885c-6411f4dc9af2.png)

**Comment by DoubangoTelecom** [comment] 2020-07-20 12:04
Duplicate of #7

**Closed by DoubangoTelecom** 2020-07-20 12:04 UTC

**Comment by DoubangoTelecom** [comment] 2020-08-07 06:52
Hello,

For information we have released the Python documentation in version 2.11.0. Recognizer sample in python: https://github.com/DoubangoTelecom/ultimateALPR-SDK/tree/master/samples/python/recognizer <https://github.com/DoubangoTelecom/ultimateALPR-SDK/tree/master/samples/python/recognizer>

Regards,
