### ISSUE TITLE
support for Khadas vim3

### ISSUE THREAD

**Issue by rsingh2083** [DoubangoTelecom/ultimateALPR-SDK#214] opened 2021-11-28 11:10 UTC
Hi,
Is there any possibility to use this SDK on Khadas Vim3 ?  (https://www.khadas.com/vim3)

**Comment by DoubangoTelecom** [comment] 2021-11-28 18:05
Duplicate of #215

**Closed by DoubangoTelecom** 2021-11-28 18:05 UTC

**Comment by DoubangoTelecom** [comment] 2021-11-28 18:13
This is an ARM64 board and if you install Linux on it the binaries at https://github.com/DoubangoTelecom/ultimateALPR-SDK/tree/master/binaries/linux/aarch64 will work. Please note that for now we don't provide commercial licenses for such arch (https://github.com/DoubangoTelecom/ultimateALPR-SDK/issues/194).

**Comment by rsingh2083** [comment] 2021-11-29 01:48
Thanks a lot for your prompt reply. Just one more clarification, aren't Jetson nano and RPI4 also ARM64 ?
If you want then we can install 32bit OS on the board in order to avail the license.

**Comment by DoubangoTelecom** [comment] 2021-11-29 02:45
You have to think by OS (L4T, Raspbian, Android...) instead of architecture (ARM 32 or 64).

Jetson nano uses LT4 operating system (ARM64), that OS cannot run on your board. Raspberry Pi is an ARM64 board but the OS (Raspbian) is 32bit. 

Your options are:
- (recommended) wait for issue #194 to be closed. You'll have fully functional arm64 OS (linux) on an arm64 board
- or, use Android OS if supported 
- or, Raspbian OS (32bit) if supported (not recommended)
