### ISSUE TITLE
Recognition accuracy issue on raspberry pi

### ISSUE THREAD

**Issue by Avadesign-David** [DoubangoTelecom/ultimateALPR-SDK#151] opened 2021-06-03 02:42 UTC
We have encounter accuracy problem with raspberry pi. It recognize the wrong word "Q" -> "0", "Z" -> "7".
But some of the image result is correct while we test it on https://www.doubango.org/webapps/alpr/

P.S.
Platform: raspberry pi 4 (32bit)
SDK version: 3.3

![60a354261e6ab2213332b740_1622613521277](https://user-images.githubusercontent.com/1132341/120577591-1e086e80-c457-11eb-8682-91d065a1a963.jpg)
![60a354261e6ab2213332b740_1622613481816](https://user-images.githubusercontent.com/1132341/120577605-219bf580-c457-11eb-8b9f-e64d089c3144.jpg)
![60a354261e6ab2213332b740_1622611225345](https://user-images.githubusercontent.com/1132341/120577606-22cd2280-c457-11eb-8e15-e7c322f667a9.jpg)
![60a354261e6ab2213332b740_1622617859617](https://user-images.githubusercontent.com/1132341/120577608-2365b900-c457-11eb-8660-4e6039b2287f.jpg)
![60a354261e6ab2213332b740_1622611419098](https://user-images.githubusercontent.com/1132341/120577610-23fe4f80-c457-11eb-88e1-b272bfe133b2.jpg)
![60a354261e6ab2213332b740_1622611226573](https://user-images.githubusercontent.com/1132341/120577612-2496e600-c457-11eb-8c10-54def4148058.jpg)

**Comment by DoubangoTelecom** [comment] 2021-06-03 02:51
As explained at https://www.doubango.org/pricing.html, the Server (x64) models are more accurate than the Mobile (ARM) models. So, that explain why the result is different from the cloud. You'll have the same result as our cloud if you try on Windows or Linux x86 instead of Raspberry Pi.
In your case the issue is that we only have very few license plates from Taiwan. If you have samples (more than 1K) we can add them to the training set to increase the accuracy.

Also consider enabling the [rectification layer](https://www.doubango.org/SDKs/anpr/docs/Configuration_options.html#recogn-rectify-enabled) to increase the accuracy.

Another note: Update your code to 3.3.2: https://github.com/DoubangoTelecom/ultimateALPR-SDK/commit/0b2f9568d58abb9935e1a3fd71c80bc4ba4ce807

**Comment by DoubangoTelecom** [comment] 2021-06-03 03:10
Tried with https://www.doubango.org/webapps/alpr/ and only one Q is misinterpreted as 0 and based on the angle it's not really a bug as it's hard even for a human.

![alt text](https://user-images.githubusercontent.com/1132341/120577591-1e086e80-c457-11eb-8682-91d065a1a963.jpg "Q misread")

I have tried your images with https://platerecognizer.com, I also have 1 error on a different image.

OpenALPR online demo is no longer available but you would probably have the same number of errors.

You should reconsider the position of your camera, enable [rectification layer](https://www.doubango.org/SDKs/anpr/docs/Configuration_options.html#recogn-rectify-enabled) or use a Linux/Windows x64 version.

**Comment by Avadesign-David** [comment] 2021-06-04 03:32
> As explained at https://www.doubango.org/pricing.html, the Server (x64) models are more accurate than the Mobile (ARM) models. So, that explains why the result is different from the cloud. You'll have the same result as our cloud if you try on Windows or Linux x86 instead of Raspberry Pi.
> In your case the issue is that we only have very few license plates from Taiwan. If you have samples (more than 1K) we can add them to the training set to increase the accuracy.
> 
> Also consider enabling the [rectification layer](https://www.doubango.org/SDKs/anpr/docs/Configuration_options.html#recogn-rectify-enabled) to increase the accuracy.
> 
> Another note: Update your code to 3.3.2: [0b2f956](https://github.com/DoubangoTelecom/ultimateALPR-SDK/commit/0b2f9568d58abb9935e1a3fd71c80bc4ba4ce807)

Okay, I understand. Although we do not have more than 1K images data, we have about 100 images. And also we can provide the characters(Taiwan license plate used) sample if needed. If these can help with improve accuracy?

**Comment by DoubangoTelecom** [comment] 2021-06-13 20:35
> > As explained at https://www.doubango.org/pricing.html, the Server (x64) models are more accurate than the Mobile (ARM) models. So, that explains why the result is different from the cloud. You'll have the same result as our cloud if you try on Windows or Linux x86 instead of Raspberry Pi.
> > In your case the issue is that we only have very few license plates from Taiwan. If you have samples (more than 1K) we can add them to the training set to increase the accuracy.
> > Also consider enabling the [rectification layer](https://www.doubango.org/SDKs/anpr/docs/Configuration_options.html#recogn-rectify-enabled) to increase the accuracy.
> > Another note: Update your code to 3.3.2: [0b2f956](https://github.com/DoubangoTelecom/ultimateALPR-SDK/commit/0b2f9568d58abb9935e1a3fd71c80bc4ba4ce807)
> 
> Okay, I understand. Although we do not have more than 1K images data, we have about 100 images. And also we can provide the characters(Taiwan license plate used) sample if needed. If these can help with improve accuracy?

You can share your images regardless the number. We'll update the model in the coming days.

**Comment by DoubangoTelecom** [comment] 2021-06-16 12:52
Google drive or any other sharing method

**Comment by Avadesign-David** [comment] 2021-06-16 13:00
Okay. We have uploaded the images. It contains about 1k images.
Download link: https://avadesign-download.s3.amazonaws.com/Car.zip

**Comment by DoubangoTelecom** [comment] 2021-12-24 01:04
Will be fixed in the next version (probably v3.7). Already pushed at https://www.doubango.org/webapps/alpr/

**Comment by DoubangoTelecom** [comment] 2022-01-12 01:39
Fixed by v3.7.0

**Closed by DoubangoTelecom** 2022-01-12 01:39 UTC
