### ISSUE TITLE
Can't recognise the last character in android.

### ISSUE THREAD

**Issue by dhruv1462** [DoubangoTelecom/ultimateALPR-SDK#33] opened 2020-02-18 17:41 UTC
When i launched your sdk and activity in android it works fine .. but everytime it fails to recognise the last character it shows * in the last character. Any suggestions???

**Comment by DoubangoTelecom** [comment] 2020-02-18 20:42
Duplicate of #13

**Closed by DoubangoTelecom** 2020-02-18 20:42 UTC
