### ISSUE TITLE
Taiwan license plate

### ISSUE THREAD

**Issue by Avadesign-David** [DoubangoTelecom/ultimateALPR-SDK#154] opened 2021-06-05 12:16 UTC
Since the accuracy is not enough for Taiwan license plate format. Can we provide some image data(few hundred) for training? 
And perhaps we can provide the characters(Taiwan license plate used) sample if needed.

**Comment by DoubangoTelecom** [comment] 2021-06-05 12:52
Duplicate of #151

**Comment by DoubangoTelecom** [comment] 2022-01-12 01:39
Fixed by v3.7.0

**Closed by DoubangoTelecom** 2022-01-12 01:39 UTC
